
server_listen:
  ip: 0.0.0.0
  port: 8080

postgre_settings:
  host: postgre
  port: 5432
  database: banners_database
  username: postgres
  password: 123

password_key: 123

cache_settings:
  size: 0
  ttl_in_minutes: 5

redis_settings:
  host: redis
  port: 6379
  password: 123
  database: 0