basePath: /
definitions:
  banner_model.BannerInsert:
    properties:
      content:
        type: string
      feature_id:
        type: integer
      is_active:
        type: boolean
      tag_id:
        items:
          type: integer
        minItems: 1
        type: array
    required:
    - content
    - feature_id
    - is_active
    - tag_id
    type: object
  transport.RespWriterBannerCreated:
    properties:
      banner_id:
        type: integer
    type: object
  transport.RespWriterError:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API сервер для сервиса баннеров
  title: Сервис баннеров
paths:
  /banner:
    post:
      consumes:
      - application/json
      description: Создание нового баннера
      operationId: create-banner
      parameters:
      - description: banner info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/banner_model.BannerInsert'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/transport.RespWriterBannerCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.RespWriterError'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.RespWriterError'
      security:
      - ApiKeyAuth: []
      summary: CreateBanner
      tags:
      - banner
  /user_banner:
    get:
      description: Получение баннера для пользователя
      operationId: get-user-banner
      parameters:
      - description: tag_id
        in: query
        name: tag_id
        required: true
        type: integer
      - description: feature_id
        in: query
        name: feature_id
        required: true
        type: integer
      - description: use_last_revision
        in: query
        name: use_last_revision
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/transport.RespWriterBannerCreated'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/transport.RespWriterError'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/transport.RespWriterError'
      security:
      - ApiKeyAuth: []
      summary: GetUserBanner
      tags:
      - banner
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
